- name: Ensure NFS common is installed.
  apt: name=nfs-common state=installed update_cache=yes

- name: Create mountable dir
  file: path=/nfs state=directory mode=777 owner=root group=root

- name: set mountpoints
  mount: name=/nfs src="127.0.0.1:/test" fstype=nfs opts=defaults dump=0 passno=2 state=mounted